#!/usr/bin/env bash
set -euo pipefail

# ─── Generate Audit Report ────────────────────────────────
# Reads JSON results and produces a markdown summary.
# Usage: ./scripts/generate-report.sh <results-dir> <output-file>

RESULTS_DIR="${1:?Missing results directory}"
OUTPUT_FILE="${2:?Missing output file}"
DATE=$(date +%Y-%m-%d)

cat > "$OUTPUT_FILE" <<EOF
# Audit Report — $DATE

Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

---

## Summary

EOF

# ─── Crawl Results ────────────────────────────────────────
CRAWL_FILE="$RESULTS_DIR/crawl-results.json"
if [ -f "$CRAWL_FILE" ]; then
  TOTAL=$(jq 'length' "$CRAWL_FILE" 2>/dev/null || echo "0")
  PASSED=$(jq '[.[] | select(.passed == true)] | length' "$CRAWL_FILE" 2>/dev/null || echo "0")
  FAILED=$((TOTAL - PASSED))

  cat >> "$OUTPUT_FILE" <<EOF
### Page Crawl Results

- **Total pages:** $TOTAL
- **Passed:** $PASSED
- **Failed:** $FAILED

| Page | Load Time (ms) | Console Errors | Broken Images | Overflow |
|------|----------------|----------------|---------------|----------|
EOF

  jq -r '.[] | "| \(.name) | \(.performance.loadComplete // "N/A") | \(.consoleErrors | length) | \(.brokenImages | length) | \(.overflowElements) |"' \
    "$CRAWL_FILE" >> "$OUTPUT_FILE" 2>/dev/null || echo "| (parse error) | — | — | — | — |" >> "$OUTPUT_FILE"

  echo "" >> "$OUTPUT_FILE"
fi

# ─── API Validation Results ───────────────────────────────
API_FILE="$RESULTS_DIR/api-validation-results.json"
if [ -f "$API_FILE" ]; then
  API_TOTAL=$(jq 'length' "$API_FILE" 2>/dev/null || echo "0")
  API_OK=$(jq '[.[] | select(.status < 400)] | length' "$API_FILE" 2>/dev/null || echo "0")

  cat >> "$OUTPUT_FILE" <<EOF
### API Validation

- **Endpoints tested:** $API_TOTAL
- **Healthy (< 400):** $API_OK

| Endpoint | Status | Response Time (ms) | Valid JSON | Expected Shape |
|----------|--------|--------------------|------------|----------------|
EOF

  jq -r '.[] | "| \(.endpoint) | \(.status) | \(.responseTimeMs) | \(.validJson) | \(.hasExpectedShape) |"' \
    "$API_FILE" >> "$OUTPUT_FILE" 2>/dev/null || echo "| (parse error) | — | — | — | — |" >> "$OUTPUT_FILE"

  echo "" >> "$OUTPUT_FILE"
fi

# ─── Performance Results ──────────────────────────────────
PERF_FILE=$(ls -t "$RESULTS_DIR"/perf-*.json 2>/dev/null | head -1)
if [ -n "$PERF_FILE" ] && [ -f "$PERF_FILE" ]; then
  cat >> "$OUTPUT_FILE" <<EOF
### Performance Metrics

| Page | LCP (ms) | CLS | TTI (ms) | DOM Content Loaded (ms) | Full Load (ms) |
|------|----------|-----|----------|-------------------------|----------------|
EOF

  jq -r '.[] | "| \(.page) | \(.lcp // "N/A") | \(.cls // "N/A") | \(.tti // "N/A") | \(.domContentLoaded) | \(.loadComplete) |"' \
    "$PERF_FILE" >> "$OUTPUT_FILE" 2>/dev/null || echo "| (parse error) | — | — | — | — | — |" >> "$OUTPUT_FILE"

  echo "" >> "$OUTPUT_FILE"
fi

# ─── Test Suite Results ───────────────────────────────────
TEST_FILE="$RESULTS_DIR/test-results.json"
if [ -f "$TEST_FILE" ]; then
  PASSED_TESTS=$(jq '.stats.expected // 0' "$TEST_FILE" 2>/dev/null || echo "0")
  FAILED_TESTS=$(jq '.stats.unexpected // 0' "$TEST_FILE" 2>/dev/null || echo "0")
  FLAKY_TESTS=$(jq '.stats.flaky // 0' "$TEST_FILE" 2>/dev/null || echo "0")
  SKIPPED_TESTS=$(jq '.stats.skipped // 0' "$TEST_FILE" 2>/dev/null || echo "0")
  TOTAL_TESTS=$((PASSED_TESTS + FAILED_TESTS + FLAKY_TESTS + SKIPPED_TESTS))

  cat >> "$OUTPUT_FILE" <<EOF
### Test Suite Summary

- **Total:** $TOTAL_TESTS
- **Passed:** $PASSED_TESTS
- **Failed:** $FAILED_TESTS
- **Skipped:** $SKIPPED_TESTS

EOF
fi

cat >> "$OUTPUT_FILE" <<EOF
---

*Report generated by \`scripts/generate-report.sh\`*
EOF

echo "Report written to $OUTPUT_FILE"
